import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/ui/global.css";
import ComicSourceProvider from "./ui/contexts/ComicSource/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ComicSourceProvider>{children}</ComicSourceProvider>
      </body>
    </html>
  );
}
